# Generated by Django 5.1.3 on 2024-12-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_products_date_created_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.store'),
        ),
    ]
