# Generated by Django 5.1.3 on 2024-12-14 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cartitem_ordered_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
