# Generated by Django 5.1.3 on 2024-12-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_ordered_order_ordered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(),
        ),
    ]
